GET http://localhost:3003/api/blogs

### GET http://localhost:3001/api/persons/65bf

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The first finded user auto added to blogs",
    "author": "Chippolino",
    "url": "http://test.ice",
    "likes": 121
}

###
PUT http://localhost:3003/api/blogs/6666f35e4445c94c55b38e5f
Content-Type: application/json

{
    "likes": 777
}

###
DELETE http://localhost:3003/api/blogs/6644df1babde576942759750

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "poooop",
    "name": "Boris",
    "password": "1234"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "poooop",
    "password": "1234"
}
